---
- hosts: 192.168.122.79
  become: true
  become_user: root

  tasks:
    - name: Parando apache
      service:
        name: httpd
        state: stopped

    - name: copy texting.txt
      copy: 
        src: /opt/testing.txt 
        dest: /etc/testing
      notify: restart_apache

  handlers:
    - name: restart_apache
      service:
        name: httpd
        state: restarted
