---
- hosts: 192.168.122.79
  become: true
  become_user: root
  become_method: sudo

  tasks:
    - name: Parando apache
      service:
        name: httpd
        state: stopped

    - name: fetch testing.txt
      fetch: 
        dest: /etc/testing.txt
        src: /etc/testing/testing.txt 
        flat: yes
      notify: restart_apache

  handlers:
    - name: restart_apache
      service:
        name: httpd
        state: restarted

