---
- name: Usando role de deploy de aplicação em JBoss EAP
  hosts: all

  tasks:
  - name: Copiando arquivo para área de deploy
    copy:
      src: ticket-monster.war
      dest: /opt/jboss-eap-7.0/standalone/deployments
